const GIFT_INFORMATION = {
	1: {
		name: "Cargador Inalámbrico",
		description: "Estación de carga MagSage para iPhone, Airpods y Apple Watch. Es importante que sea de carga rápida para que no tarde mil vidas en cargar.",
		price: 583.99,
		image: "https://m.media-amazon.com/images/I/619i8DIQy+L._AC_SL1500_.jpg",
		link: "https://a.co/d/1tqIayK",
		otherPlaces: ["iShop", "Liverpool", "Sears", "Mercado Libre"],
	},
	2: {
		name: "Sudadera",
		description: "Sudadera con capucha y bolsillo canguro de Hollister",
		price: 787.58,
		image: "https://img.hollisterco.com/is/image/anf/KIC_322-4176-00210-200_model1.jpg",
		link: "https://www.hollisterco.com/shop/wd-es/p/sudadera-holgada-con-capucha-y-logo-58565821?categoryId=12572&faceout=model&seq=16",
		otherPlaces: ["Liverpool", "Sears", "Hollister Satélite", "Hollister Perisur"],
	},
	3: {
		name: "Bateria externa",
		description: "Batería externa de 20,000mAh con 4 puertos de carga",
		price: 588.55,
		image: "https://m.media-amazon.com/images/I/71ManMP7pZL._AC_SL1500_.jpg",
		link: "https://a.co/d/alWVTil",
		otherPlaces: ["iShop", "Liverpool", "Sears", "Mercado Libre"],
	},
	4: {
		name: "Kindle",
		description: "Lector de libros electrónicos con luz frontal ajustable",
		price: 2099.0,
		image: "https://m.media-amazon.com/images/I/71w-4uiDzoL._AC_SL1500_.jpg",
		link: "https://a.co/d/g7CsPbQ",
		otherPlaces: ["MixUp", "Liverpool", "Sears"],
	},
	5: {
		name: "Cápsulas de café Nespresso Vertuo",
		description: "Cápsulas de café Nespresso Vertuo, mis favoritas son: Il Caffè, Diavolito, Melozio e Intenso",
		price: 0.0,
		image: "https://m.media-amazon.com/images/I/61K9nWSTB6L.jpg",
		link: "https://www.nespresso.com/mx/es/order/capsules/vertuo",
		otherPlaces: ["Nespresso Satélite", "Palacio de Hierro"],
	},
	6: {
		name: "Sudadera nacota de Calvin Klein",
		description: "Sudadera con capucha y bolsillo canguro de Calvin Klein",
		price: 2499.0,
		image: "https://calvinkleinmx.vteximg.com.br/arquivos/ids/506646-1764.1000000000001-1923/J30J320805P41-PLANO.jpg",
		link: "https://www.calvinklein.mx/sudadera-calvin-klein-monologo-mujer-gris-j30j320805-p41/p",
		otherPlaces: ["Liverpool", "Sears", "Calvin Klein Perisur", "Calvin Klein Santa Fe", "Calvin Klein Satélite"],
	},
};
