const GIFT_INFORMATION = {
	1: {
		name: "Cargador Inalámbrico",
		description: "Estación de carga MagSage para iPhone, Airpods y Apple Watch. Es importante que sea de carga rápida para que no tarde mil vidas en cargar.",
		price: 583.99,
		image: "https://m.media-amazon.com/images/I/619i8DIQy+L._AC_SL1500_.jpg",
		link: "https://a.co/d/1tqIayK",
		otherPlaces: ["iShop", "Liverpool", "Sears", "Mercado Libre"],
	},
	2: {
		name: "Sudadera",
		description: "Sudadera con capucha y bolsillo canguro de Hollister",
		price: 787.58,
		image: "https://img.hollisterco.com/is/image/anf/KIC_322-4176-00210-200_model1.jpg",
		link: "https://www.hollisterco.com/shop/wd-es/p/sudadera-holgada-con-capucha-y-logo-58565821?categoryId=12572&faceout=model&seq=16",
		otherPlaces: ["Liverpool", "Sears", "Hollister Satélite", "Hollister Perisur"],
	},
	3: {
		name: "Bateria externa",
		description: "Batería externa de 20,000mAh con 4 puertos de carga",
		price: 588.55,
		image: "https://m.media-amazon.com/images/I/71ManMP7pZL._AC_SL1500_.jpg",
		link: "https://a.co/d/alWVTil",
		otherPlaces: ["iShop", "Liverpool", "Sears", "Mercado Libre"],
	},
	4: {
		name: "Kindle",
		description: "Lector de libros electrónicos con luz frontal ajustable",
		price: 2099.0,
		image: "https://m.media-amazon.com/images/I/71w-4uiDzoL._AC_SL1500_.jpg",
		link: "https://a.co/d/g7CsPbQ",
		otherPlaces: ["MixUp", "Liverpool", "Sears"],
	},
	5: {
		name: "Cápsulas de café Nespresso Vertuo",
		description: "Cápsulas de café Nespresso Vertuo, mis favoritas son: Il Caffè, Diavolito, Melozio e Intenso",
		price: 170.0,
		image: "https://m.media-amazon.com/images/I/61K9nWSTB6L.jpg",
		link: "https://www.nespresso.com/mx/es/order/capsules/vertuo",
		otherPlaces: ["Nespresso Satélite", "Palacio de Hierro"],
	},
	6: {
		name: "Sudadera nacota de Calvin Klein",
		description: "Sudadera con capucha y bolsillo canguro de Calvin Klein",
		price: 2499.0,
		image: "https://calvinkleinmx.vteximg.com.br/arquivos/ids/506646-1764.1000000000001-1923/J30J320805P41-PLANO.jpg",
		link: "https://www.calvinklein.mx/sudadera-calvin-klein-monologo-mujer-gris-j30j320805-p41/p",
		otherPlaces: ["Liverpool", "Sears", "Calvin Klein Perisur", "Calvin Klein Santa Fe", "Calvin Klein Satélite"],
	},
	7: {
		name: "Eau de parfum Polo Ralph Lauren Ralph's Club para hombre",
		description: "os ingredientes de origen natural, producidos artesanalmente para Ralph Lauren con la máxima calidad, dejan una estela persistente que te llevará hasta la noche.",
		price: 3500.0,
		image: "https://ss701.liverpool.com.mx/xl/1127310421.jpg",
		link: "https://www.liverpool.com.mx/tienda/pdp/eau-de-parfum-polo-ralph-lauren-ralph's-club-para-hombre/1127309501",
		otherPlaces: ["Palacio de Hierro", "Sears"],
	},
	8: {
		name: "Jeans coreanezcos negros Hollister",
		description: "Jeans rectos negros que no se decoloran",
		price: 984.72,
		image: "https://img.hollisterco.com/is/image/anf/KIC_331-2230-2834-975_model2.jpg",
		link: "https://www.hollisterco.com/shop/wd-es/p/black-no-fade-straight-jeans-50236419-1002?categoryId=12589&faceout=model&seq=11",
		otherPlaces: ["Liverpool", "Sears", "Palacio de Hierro"],
	},
	9: {
		name: "Jeans Coreanezco claro Hollister",
		description: "Jeans holgados con lavado claro",
		price: 984.72,
		image: "https://img.hollisterco.com/is/image/anf/KIC_331-4114-00093-280_model2.jpg",
		link: "https://www.hollisterco.com/shop/wd-es/p/light-wash-loose-jeans-57207325-1002?categoryId=12589&faceout=model&seq=25",
		otherPlaces: ["Liverpool", "Sears", "Palacio de Hierro"],
	},
	10: {
		name: "Mario + Rabbids® Sparks of Hope edición Gold",
		description: "Haz equipo con Mario, Luigi, la princesa Peach, Rabbid Peach, Rabbid Luigi y sus amigos en un viaje galáctico para derrotar a una entidad malvada y salvar a tus compañeros Spark. ¡Explora planetas a través de la galaxia conforme descubres misteriosos secretos y disfrutas de atractivas misiones!",
		price: 653.0,
		image: "https://platform.polygon.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/24124990/sparks_hope_guides.jpg",
		link: "https://www.nintendo.com/es-mx/store/products/mario-plus-rabbids-sparks-of-hope-gold-edition-switch/",
		otherPlaces: ["Game Planet", "Liverpool", "Sears", "Palacio de Hierro", "Sanborns", "Amazon"],
	},
	11: {
		name: "MARIO STRIKERS BATTLE LEAGUE",
		description: "Les presentamos Strike, un deporte de 5 contra 5 inspirado en el fútbol donde no hay reglas, ¡así que haz lo que tengas que hacer para conseguir la victoria! Juega con determinación e intenta anotar el mayor número de goles al superar a tus enemigos con entradas, usar objetos y lanzar tiros especiales que incrementarán tu puntuación. Personajes conocidos de la serie Super Mario, como Peach, Toad y Yoshi, llegarán con sus zapatillas de fútbol (y sus estadísticas) a la cancha y no se detendrán ante nada para anotar.",
		price: 1000.0,
		image: "https://cdn.gameplanet.com/wp-content/uploads/2022/09/05065152/mario-strikers-battle-league_1-510x630.jpg",
		link: "https://gameplanet.com/producto/mario-strikers-battle-league-nsw/",
		otherPlaces: ["Nintendo eShop", "Liverpool", "Sears", "Palacio de Hierro", "Sanborns", "Amazon"],
	},
};
